image: node

stage:
  - teste
  - package
  - deploy

cache:
  paths:
    - ./website/build

before_script:
  - whoami
  - pwd

teste site:
  stage: test
  before_script:
    - npm install -g broken-link-checker wait-on
  script:
    - cd website
    - npm install && npm run start &
    - wait-on http://localhost:3000 --timeout 30000
    - blc --recursive --exclude-external http://localhost:3000

package site:
  stage: package
  artifacts:
   name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
   when: always
   expire_in: 2h20min
   paths:
     - ./website/build/missaodevops


  script:
    - cd website
    - npm install	
    - npm run build 

deploy to stagin:
  stage: deploy
  before_script:
    - npm install -g surge
  script: 
    - surge --project ./website/build/missaodevops --domain missaodevops
 
  after_script:
    - whoami
  environment:
    name: staging
    url: http://missaodevops-rc.surge.sh
  only:
   - develop
  