image: node

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - ./website/build

before_script:
  - whoami
  - pwd

teste site:

build site:
  stage: build
  artifacts:
   name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
   when: always
   expire_in: 2h20min
   paths:
     - ./website/build/missaodevops


  script:
    - cd website
    - npm install	
    - npm run build 

deploy to stagin:
  stage: deploy
  before_script:
    - npm install -g surge
  script: 
    - surge --project ./website/build/missaodevops --domain missaodevops
 
  after_script:
    - whoami
  environment:
    name: staging
    url: http://missaodevops-rc.surge.sh
  only:
   - develop
  